service: aws-git-codeploy
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 256
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"
  environment:
    GIT_WEBHOOK_USERNAME: ''
    GIT_WEBHOOK_TOKEN: ''
    GIT_WEBHOOK_SECRET: ''
    S3_BUCKET: ''

package:
  exclude:
    - ".vscode/**"
    - ".idea/**"

functions:
  api:
    handler: index.handler
    layers:
      - arn:aws:lambda:us-east-1:553035198032:layer:git-lambda2:8
    events:
      - http:
          path: /
          method: POST
          cors: true

plugins:
  - serverless-offline
